=== danila16030/thirdTaskEpam/data/banks.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.learn.by/banks"
           elementFormDefault="qualified">
    <xs:element name="Banks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Bank" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Country" type="xs:string"/>
                            <xs:element name="Depositor" type="xs:string"/>
                            <xs:element name="AccountId" type="xs:int" default="0000"/>
                            <xs:element name="AmountOfDeposit" type="xs:int"/>
                            <xs:element name="Profitability" type="xs:double"/>
                            <xs:element name="TimeConstraints" type="xs:int"/>
                        </xs:sequence>
                        <xs:attribute name="Type" type="typ"/>
                        <xs:attribute name="id" type="xs:int"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="typ">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PosteRestante"/>
            <xs:enumeration value="Urgent"/>
            <xs:enumeration value="Estimated"/>
            <xs:enumeration value="Funded"/>
            <xs:enumeration value="Saving"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== danila16030/thirdTaskEpam/data/banks.xml
<?xml version="1.0" encoding="UTF-8"?>

<Banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.learn.by/banks"
       xsi:schemaLocation="http://www.learn.by/banks  banks.xsd">



    <Bank id="1">
        <Name>National</Name>
        <Country>Belarus</Country>
        <Depositor>Danila</Depositor>
        <AccountId>1234</AccountId>
        <AmountOfDeposit>12365</AmountOfDeposit>
        <Profitability>1.0</Profitability>
        <TimeConstraints>15</TimeConstraints>
    </Bank>

    <Bank id="2" Type="Saving">
        <Name>National</Name>
        <Country>USA</Country>
        <Depositor>Danila</Depositor>
        <AccountId>9876</AccountId>
        <AmountOfDeposit>12</AmountOfDeposit>
        <Profitability>1.98</Profitability>
        <TimeConstraints>8</TimeConstraints>
    </Bank>


    <Bank id="3" Type="PosteRestante" >
        <Name>National</Name>
        <Country>Ukraine</Country>
        <Depositor>Danila</Depositor>
        <AccountId>756</AccountId>
        <AmountOfDeposit>1</AmountOfDeposit>
        <Profitability>99</Profitability>
        <TimeConstraints>12</TimeConstraints>
    </Bank>


    <Bank id="4" Type="Funded">
        <Name>National</Name>
        <Country>Rus</Country>
        <Depositor>Danila</Depositor>
        <AccountId>9756</AccountId>
        <AmountOfDeposit>471</AmountOfDeposit>
        <Profitability>0.98</Profitability>
        <TimeConstraints>1</TimeConstraints>
    </Bank>



</Banks>
